const volumeProps = [
  "DT_NONE",
  "DT_UNKNOWN",
  "DT_BINARY",
  "DT_UNSIGNED_CHAR",
  "DT_SIGNED_SHORT",
  "DT_SIGNED_INT",
  "DT_FLOAT",
  "DT_COMPLEX",
  "DT_DOUBLE",
  "DT_RGB",
  "DT_ALL",
  "DT_INT8",
  "DT_UINT16",
  "DT_UINT32",
  "DT_INT64",
  "DT_UINT64",
  "DT_FLOAT128",
  "DT_COMPLEX128",
  "DT_COMPLEX256",
  "DT_RGBA32",
  "name",
  "id",
  //"_colormap",
  //"_opacity",
  "percentileFrac",
  "ignoreZeroVoxels",
  "trustCalMinMax",
  "colormapNegative",
  "frame4D",
  "cal_minNeg",
  "cal_maxNeg",
  "colorbarVisible",
  "visible",
  "modulationImage",
  "modulateAlpha",
  //series: daikon.Series;
  "hdr",

  "cal_min",
  "cal_max",
  "robust_min",
  "robust_max",
  "global_min",
  "global_max",

  "imageType",
  "nFrame4D",
  "nTotalFrame4D",
  "nVox3D",
  "img",
  "oblique_angle",
  "obliqueRAS",
  "maxShearDeg",
  "frac2mm",
  "frac2mmOrtho",
  "mm2ortho",
  "toRAS",
  "matRAS",
  "extentsMinOrtho",
  "extentsMaxOrtho",
  "pixDimsRAS",
  "dimsRAS",
  "permRAS",
  "toRASvox",
  "useQFormNotSForm",
  //fileObject?: File | null;
  "url",

  "mm000",
  "mm100",
  "mm010",
  "mm001",
];

const meshProps = [
  "name",
  "colorbarVisible",
  "id",
  "furthestVertexFromOrigin",
  "extentsMin",
  "extentsMax",
  "opacity",
  "visible",
  "meshShaderIndex",
  //indexBuffer: WebGLBuffer | null;
  //vertexBuffer: WebGLBuffer | null;
  //vao: WebGLVertexArrayObject | null;
  //"offsetPt0",
  "hasConnectome",
  "connectome",
  //"pts",
  "layers",
  "rgba255",
  "fiberLength",
  "fiberLengths",
  "fiberDither",
  "fiberColor",
  "fiberDecimationStride",
  "fiberMask",
  "colormap",
  //"dpg",
  //"dps",
  //"dpv",
  "tris",
  "indexCount",
  "nodes",
  "edges",
  "nodeScale",
  "edgeScale",
  "nodeColormap",
  "edgeColormap",
  "nodeColormapNegative",
  "nodeMinColor",
  "nodeMaxColor",
  "edgeColormapNegative",
  "edgeMin",
  "edgeMax",
  "vertexCount",
];

const layerProps = [
  "url",
  "opacity",
  "colormap",
  "colormapNegative",
  "useNegativeCmap",
  "cal_min",
  "cal_max",
  
  //values: Uint32Array | never[];
  "frame4D",
  "isTransparentBelowCalMin",
  "isOutlineBorder",
  "cal_minNeg",
  "cal_maxNeg",

  "nFrame4D",
];

var constants = {volumeProps, meshProps, layerProps};